pipeline {
    agent  {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "490004627649"
        PROJECT = "expense"
        COMPONENT = "backend"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    parameters {
        booleanParam(name: 'deploy', defaultValue: false, description: 'Toggle this value')
    }
     // Build
    stages {
         stage('Read package.json') {
            steps {
                dir('expense-backend/expense-ci/backend') {
                    script {
                        def packageJson = readJSON file: 'package.json'
                        appVersion = packageJson.version
                        echo "Package version: ${appVersion}"
                    }
                }   
            }
        }
    /* stage('Install Dependencies') {
            steps {
                script {
                   sh """
                        npm install
                   """
                }
            }
        } */
    stage('Docker Build') {
        steps {
            dir('expense-backend/expense-ci/backend'){
            script {
                withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                    sh """
                        aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com
                        docker build \
                            --platform=linux/amd64 \
                            --provenance=false \
                            --sbom=false \
                            -t ${ACC_ID}.dkr.ecr.${REGION}.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion} .
                        docker push ${ACC_ID}.dkr.ecr.us-east-1.amazonaws.com/${PROJECT}/${COMPONENT}:${appVersion}
                    """
                    }
                }
            }
        }
    }
    stage('Trigger frontend') {
            steps {
                script {
                    build job: 'frontend', 
                      propagate: false,  // even SG fails VPC will not be effected
                      wait: false // VPC will not wait for SG pipeline completion
                }
            }
        }
    /* stage('Trigger Deploy') {
            when{
                expression { params.deploy }
            }
            steps {
                script {
                    build job: 'expense-frontend',
                    parameters: [
                        string(name: 'appVersion', value: "${appVersion}"),
                        string(name: 'deploy_to', value: 'dev')
                    ],
                    propagate: false,  // even frontend fails backend will not be effected
                    wait: false // backend will not wait for frontend pipeline completion
                }
            }
        } */
        
    }

    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        success { 
            echo 'Hello Success'
        }
        failure { 
            echo 'Hello Failure'
        }
    }
}
