pipeline {
    agent  {
        label 'AGENT-1'
    }
    environment { 
        appVersion = ''
        REGION = "us-east-1"
        ACC_ID = "160885265516"
        PROJECT = "expense"
        COMPONENT = "mysql"
    }
    options {
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    parameters {
        string(name: 'appVersion', description: 'Image version of the application')
        choice(name: 'deploy_to', choices: ['roboshop-cluster-v2', 'qa', 'prod'], description: 'Pick the Environment')
    }
    stages {

        stage('Deploy') {
                steps {
                    dir('expense-backend/expense-cd/mysql'){
                    script {
                        withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                            sh """
                                aws eks update-kubeconfig --region $REGION --name "${params.deploy_to}"
                                kubectl get nodes
                                kubectl apply -f namespace.yaml
                                sed -i "s/IMAGE_VERSION/${params.appVersion}/g" values.yaml
                                helm upgrade --install $COMPONENT -f values.yaml -n $PROJECT .
                                #kubectl apply -f application.yaml
                            """
                        }
                    }
                }
                }
            }
        /* stage('Check Status'){
                steps{
                    script{
                        withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                            def deploymentStatus = sh(returnStdout: true, script: "kubectl rollout status statefulset/mysql-statefulset --timeout=30s -n $PROJECT || echo FAILED").trim()
                            if (deploymentStatus.contains("successfully rolled out")) {
                                echo "Deployment is success"
                            } else {
                                sh """
                                    helm rollback $COMPONENT -n $PROJECT
                                    sleep 20
                                """
                                def rollbackStatus = sh(returnStdout: true, script: "kubectl rollout status deployment/mysql --timeout=30s -n $PROJECT || echo FAILED").trim()
                                if (rollbackStatus.contains("successfully rolled out")) {
                                    error "Deployment is Failure, Rollback Success"
                                }
                                else{
                                    error "Deployment is Failure, Rollback Failure. Application is not running"
                                }
                            }

                        }
                    }
                }
            } */
    }
}